default:

    compare_pams:
        paths:
          path_pams_base: /PATH/TO/BASE_PAMS.xlsx
          path_pams_compare: /PATH/TO/COMPARE_PAMS.xlsx

        thresholds:
            company_id_threshold: 25
            sectoral_production_threshold: 25

    compare_pams_banks_eo:
        paths:
            path_pams: /PATH/TO/PAMS.xlsx
            path_banks_eo: /PATH/TO/BANKS_EO.xlsx

        thresholds:
            share_rows_replicated: 0.99
            relative_tolerance_production: 0.01
            relative_tolerance_emission_factor: 0.01
