default:

    paths:
        path_pams_base: /PATH/TO/BASE_PAMS.xlsx
        path_pams_compare: /PATH/TO/COMPARE_PAMS.xlsx

    thresholds:
        company_id_threshold: 25
        sectoral_production_threshold: 25
